### PR TITLE
fix: properly compute iOS visual viewport

### LINKED ISSUE #1065: Measure viewport properly on iOS
### CodePen demo

https://6z5bu.csb.app/
https://codesandbox.io/s/loving-feather-6z5bu

### Steps to reproduce the problem

1. open demo in xcode simulator
2. hardware -> keyboard -> toggle software keyboard
3. click on input
4. scroll page up
5. flip happens only when input is overlapped by keyboard

### What is the expected behavior?

Flip should happen when without overlapping by software keyboard

### What went wrong?

Mobile browsers decided to not consider software keyboard in window height and instead overlap part of viewport. At some point this prevents junking of measured layout. Though the problem comes when we try to implement custom autocomplete.

### Any other comments?

I tried to fix this problem in our popup with many ways and end up with hardcoded keyboard size took from article. Though I searched for the problem again and found probably new api which may solve the problem.
https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API

This solved maxSize plugin for me and prevented overlapped items.
```
const keyboardHeight = window.innerHeight - window.visualViewport.height
```

Perhaps popper could use this api for viewport measuring and fallback to window when it does not exist. Solution does not require any iOS detection.

### PR DESCRIPTION
**Pull request by FezVrasta**
fixes #1065

### CODE REVIEW

File: src/dom-utils/getViewportRect.js [hunk 1]
```diff
@@ -3,10 +3,11 @@ import getWindow from './getWindow';
 
 export default function getViewportRect(element: Element) {
   const win = getWindow(element);
+  const visualViewport = win.visualViewport;
 
   return {
-    width: win.innerWidth,
-    height: win.innerHeight,
+    width: visualViewport.width || win.innerWidth,
+    height: visualViewport.height || win.innerHeight,
```
Comment (atomiks) [inline src/dom-utils/getViewportRect.js:10]: This will error if `visualViewport` is undefined

File: src/dom-utils/getViewportRect.js [hunk 2]
```diff
@@ -3,10 +3,11 @@ import getWindow from './getWindow';
 
 export default function getViewportRect(element: Element) {
   const win = getWindow(element);
+  const visualViewport = win.visualViewport || {};
 
   return {
-    width: win.innerWidth,
-    height: win.innerHeight,
+    width: visualViewport.width || win.innerWidth,
```
Comment (atomiks) [inline src/dom-utils/getViewportRect.js:9]: Is the optional chaining operator supported in flow? `win.visualViewport?.width`

Comment (FezVrasta) [reply src/dom-utils/getViewportRect.js:9]: It is, but we don’t have the right Babel plugin I think. And I think it would produce a larger output
