### PR TITLE
fix: firefox offsetParent check

### LINKED ISSUE #1043: [Firefox] wrong positioning after switching from relative to fixed positioned parent
### CodePen demo
https://codepen.io/fothermucker/pen/mdJaRLq

### Steps to reproduce the problem

1. Open the demo in firefox
2. Scroll the page

### What is the expected behavior?

The tooltip should stay close to the element, as it happens in google chrome

### What went wrong?

The tooltip element starts to move down when you scroll

### Any other comments?

I have a component that implements a sticky behavior in order to have better support and it works 
just like this demo. You have a container element that wraps all the sticky elements, when the scroll hits the position of the `sticky-container` it puts a class to the `sticky-element` (`.fixed`) and the element stays at the top of the window and the reference element of the popper is inside of this `sticky-element`.

This bug doesn't happen in chrome or safari.

Thx guys :)

### PR DESCRIPTION
**Pull request by atomiks**
Resolves #1043 (and fixed incorrect behavior for #837)

### CODE REVIEW

File: src/dom-utils/getOffsetParent.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ function getTrueOffsetParent(element: Element): ?Element {
     !isHTMLElement(element) ||
     !(offsetParent = element.offsetParent) ||
```
Comment (FezVrasta) [inline src/dom-utils/getOffsetParent.js]: Do we need this assignment?
