### PR TITLE
fix: rewrite clippingRect logic

### LINKED ISSUE #1097: Wrong tooltip positions when X axis has overflow (on mobile)
### CodeSandbox demo

gistcdn.githack.com/FezVrasta/11b807834b33667c5d6d5422f0f6258c/raw/34fdc52bf041388bb3f57e4c94690ddfcf684a14/bug.html

(you need to open the dev tools and go in the mobile emulation mode)

### Steps to reproduce the problem

1. 
2.
3.

### PR DESCRIPTION
**Pull request by atomiks**
Attempt to close #1097

### CODE REVIEW

File: src/dom-utils/getViewportRect.js [hunk 1]
```diff
@@ -1,20 +1,30 @@
...
   // We don't know which browsers have buggy or odd implementations of this, so
   // for now we're only applying it to iOS to fix the keyboard issue.
   // Investigation required
-  if (visualViewport && /iPhone|iPod|iPad/.test(navigator.platform)) {
+  if (visualViewport) {
     width = visualViewport.width;
     height = visualViewport.height;
+
+    // Not Safari (which uses visual viewport by default)
+    if (!/^((?!chrome|android).)*safari/i.test(navigator.userAgent)) {
```
Comment (atomiks) [inline src/dom-utils/getViewportRect.js:23]: This is terrible; need to figure out a way to feature detect Safari's differences

File: src/dom-utils/getViewportRect.js [hunk 2]
```diff
@@ -13,6 +13,11 @@ export default function getViewportRect(element: Element) {
   let x = 0;
   let y = 0;
 
+  // NB: This isn't supported on iOS <= 12. If the keyboard is open, the popper
+  // can be obscured underneath it.
+  // Also, `html.clientHeight` adds the bottom bar height in Safari iOS, even
+  // if it isn't open, so if this isn't available, the popper will be detected
+  // to overflow the bottom of the screen too early.
```
Comment (atomiks) [inline src/dom-utils/getViewportRect.js:20]: We could add the `HACK` for iOS <=12's bottom bar like before, but we still have that keyboard issue. iOS 13+ works fine without any hack.
